### ISSUE TITLE
MQTT Configuration issue

### ISSUE THREAD

**Issue by mkocus** [diyruz/flower#11]
Hello,
got the following configuration issue on assembled device:
```
INFO: Starting interview of '0x00124b00220281c6'
INFO: Successfully interviewed '0x00124b00220281c6', device has successfully been paired
INFO: Device '0x00124b00220281c6' is supported, identified as: DIYRuZ [Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)
INFO: Configuring '0x00124b00220281c6'
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"[Flower sensor](http://modkam.ru/?p=1700)","friendly_name":"0x00124b00220281c6","model":"DIYRuZ_Flower","supported":true,"vendor":"DIYRuZ"},"type":"pairing"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/soil_moisture/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"icon":"mdi:water-percent","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 soil moisture","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_soil_moisture_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.soil_moisture }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 battery","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/illuminance/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"illuminance","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 illuminance","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_illuminance_zigbee2mqtt","unit_of_measurement":"-","value_template":"{{ value_json.illuminance }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/humidity/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"humidity","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 humidity","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/pressure/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"pressure","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 pressure","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_pressure_zigbee2mqtt","unit_of_measurement":"hPa","value_template":"{{ value_json.pressure }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/temperature_ds/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 temperature ds","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_temperature_ds_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature_ds }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/temperature_bme/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 temperature bme","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_temperature_bme_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature_bme }}"}'
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700)
INFO: MQTT publish: topic 'homeassistant/sensor/0x00124b00220281c6/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00124b00220281c6"],"manufacturer":"DIYRuZ","model":"[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)","name":"0x00124b00220281c6","sw_version":"Zigbee2MQTT 1.17.0"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x00124b00220281c6","name":"0x00124b00220281c6 linkquality","state_topic":"zigbee2mqtt/0x00124b00220281c6","unique_id":"0x00124b00220281c6_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
ERROR: Failed to configure '0x00124b00220281c6', attempt 1 (Error: Bind 0x00124b00220281c6/1 genPowerCfg from '0x00212effff065bda/1' failed (Error: status: 140) at DeconzAdapter.<anonymous> (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:660:23) at Generator.next (<anonymous>) at fulfilled (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter/deconzAdapter.js:24:58))
```

My hardware configuration is:
- modkam.ru flower sensor, running 2.0.5 firmware
- rasberry pi running Home Assistant (latest version)
- Conbee2 zigbee coordinator
- Zigbee2MQTT

Any ideas?

**Comment by mkocus** [comment]
It seems that the issue was caused by the zigbee interference or badly assembled sensor. I've assembled 2 more, and didn't have that issue again. Closing.
