### ISSUE TITLE
Z2M Converter - failed to start Z2M

### ISSUE THREAD

**Issue by Stephan-Fis** [diyruz/flower#57]
Hi there,

I tried to use the z2m-converter inside of homeassistant addon Z2M.
I changed the external_converters to this:
![image](https://github.com/diyruz/flower/assets/63310273/0be742d5-e5c1-4fa9-8a31-42d18eca7d8e)

And copied the file with that name next to the configuration.yaml

I then get this error message.
```
[10:41:07] INFO: Preparing to start...
[10:41:07] INFO: Socat not enabled
[10:41:07] INFO: Starting Zigbee2MQTT...

/app/node_modules/zigbee-herdsman-converters/index.js:52
    assert.ok(Array.isArray(definition.exposes) || typeof definition.exposes === 'function', 'Exposes incorrect');
           ^
AssertionError [ERR_ASSERTION]: Exposes incorrect
    at validateDefinition (/app/node_modules/zigbee-herdsman-converters/index.js:52:12)
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:73:5)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
```

Did I copied the file to the wrong location?
Is there a newer version available?

**Comment by Stephan-Fis** [comment]
Converter already integrated in "normal" Z2M-Package
